### ISSUE TITLE
Update contributing docs, `build error` for `docs-app`

### ISSUE THREAD

**Issue by nicolechung** [CrowdStrike/ember-headless-table#13]
I can't seem to run `docs-app` locally.

## What I have tried
1. `cd ember-headless-table`
2. `npm run build`
3. `cd ../docs-app`
4. `npm run build`

Resulting Error:
```
t[1].rules[3].use[0]!$TMPDIR/embroider/82e5dd/docs-app/assets/styles.css
1 | throw new Error("Module build failed (from ../../../../../../../../../Users/nchung/OpenSource/ember-headless-table/node_modules/.pnpm/postcss-loader@7.0.1_sat2ilddhdkv6huwh4d4inpfry/node_modules/postcss-loader/dist/cjs.js):\nError: Cannot find module '/Users/nchung/OpenSource/ember-headless-table/docs-app/node_modules/ember-headless-table/dist/index.js'\n    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)\n    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)\n    at resolveExports (node:internal/modules/cjs/loader:482:14)\n    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)\n    at Function.resolve (node:internal/modules/cjs/helpers:108:19)\n    at /Users/nchung/OpenSource/ember-headless-table/node_modules/.pnpm/@crowdstrike+ember-oss-docs@1.0.17_j3geqmrlntvc2i6fu2a7u3cpuy/node_modules/@crowdstrike/ember-oss-docs/tailwind.cjs:22:50\n    at Array.map (<anonymous>)\n    at tailwindConfig (/Users/nchung/OpenSource/ember-headless-table/node_modules/.pnpm/@crowdstrike+ember-oss-docs@1.0.17_j3geqmrlntvc2i6fu2a7u3cpuy/node_modules/@crowdstrike/ember-oss-docs/tailwind.cjs:21:48)\n    at Object.<anonymous> (/Users/nchung/OpenSource/ember-headless-table/docs-app/tailwind.config.js:6:16)");
 @ ./app.ts 3:0-29
 @ ./assets/docs-app.js 5:13-33 219:6-23

ERROR in ./components/docfy-demo-index-demo-a.js 13:0-53
Module not found: Error: Can't resolve 'ember-headless-table' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-index-demo-a.js 14:0-52
Module not found: Error: Can't resolve 'ember-headless-table/plugins' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-index-demo-a.js 15:0-104
Module not found: Error: Can't resolve 'ember-headless-table/plugins/column-resizing' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-index-demo-a.js 16:0-136
Module not found: Error: Can't resolve 'ember-headless-table/plugins/column-reordering' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-index-demo-a.js 17:0-115
Module not found: Error: Can't resolve 'ember-headless-table/plugins/column-visibility' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-index-demo-a.js 18:0-105
Module not found: Error: Can't resolve 'ember-headless-table/plugins/data-sorting' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-column-reordering-dema-a.js 5:0-53
Module not found: Error: Can't resolve 'ember-headless-table' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-column-reordering-dema-a.js 6:0-52
Module not found: Error: Can't resolve 'ember-headless-table/plugins' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-column-reordering-dema-a.js 7:0-103
Module not found: Error: Can't resolve 'ember-headless-table/plugins/column-reordering' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-column-reordering-dema-a.js 8:0-82
Module not found: Error: Can't resolve 'ember-headless-table/plugins/column-visibility' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-column-resizing-demo-a.js 6:0-53
Module not found: Error: Can't resolve 'ember-headless-table' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-column-resizing-demo-a.js 7:0-82
Module not found: Error: Can't resolve 'ember-headless-table/plugins/column-visibility' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-column-resizing-demo-a.js 8:0-104
Module not found: Error: Can't resolve 'ember-headless-table/plugins/column-resizing' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-column-visibility-demo-a.js 5:0-53
Module not found: Error: Can't resolve 'ember-headless-table' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-column-visibility-demo-a.js 6:0-52
Module not found: Error: Can't resolve 'ember-headless-table/plugins' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-column-visibility-demo-a.js 7:0-94
Module not found: Error: Can't resolve 'ember-headless-table/plugins/column-visibility' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-data-sorting-demo-a.js 12:0-53
Module not found: Error: Can't resolve 'ember-headless-table' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

ERROR in ./components/docfy-demo-plugins-data-sorting-demo-a.js 13:0-118
Module not found: Error: Can't resolve 'ember-headless-table/plugins/data-sorting' in '$TMPDIR/embroider/82e5dd/docs-app/components'
 @ ./assets/docs-app.js

18 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.74.0 compiled with 20 errors in 6162 ms
cleaning up...
Build Error (PackagerRunner) in assets/styles.css.webpack[javascript/auto]!=!/Users/nchung/OpenSource/ember-headless-table/node_modules/.pnpm/css-loader@5.2.7_webpack@5.74.0/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!/Users/nchung/OpenSource/ember-headless-table/node_modules/.pnpm/postcss-loader@7.0.1_sat2ilddhdkv6huwh4d4inpfry/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[0]!/private/var/folders/hv/81bcz3j93bxd_ytql39t_4nw0000gn/T/embroider/82e5dd/docs-app/assets/styles.css

Module build failed (from ../../../../../../../../../Users/nchung/OpenSource/ember-headless-table/node_modules/.pnpm/postcss-loader@7.0.1_sat2ilddhdkv6huwh4d4inpfry/node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module '/Users/nchung/OpenSource/ember-headless-table/docs-app/node_modules/ember-headless-table/dist/index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/nchung/OpenSource/ember-headless-table/node_modules/.pnpm/@crowdstrike+ember-oss-docs@1.0.17_j3geqmrlntvc2i6fu2a7u3cpuy/node_modules/@crowdstrike/ember-oss-docs/tailwind.cjs:22:50
    at Array.map (<anonymous>)
    at tailwindConfig (/Users/nchung/OpenSource/ember-headless-table/node_modules/.pnpm/@crowdstrike+ember-oss-docs@1.0.17_j3geqmrlntvc2i6fu2a7u3cpuy/node_modules/@crowdstrike/ember-oss-docs/tailwind.cjs:21:48)
    at Object.<anonymous> (/Users/nchung/OpenSource/ember-headless-table/docs-app/tailwind.config.js:6:16)
    ```
    
    5. `npm run start` also errors with the same `postcss-loader` error.

**Comment by NullVoxPopuli** [comment]
can you try with:
```
pnpm install
pnpm build
cd docs-app
pnpm start
```
?

**Comment by NullVoxPopuli** [comment]
also, discovered in here: https://github.com/NullVoxPopuli/ember-ci-update/commit/ad39c9aad80c34dcc46b3bfde6e3b238ae05a31a

until: https://github.com/pnpm/pnpm/issues/4965 is fixed, you may need to (before running `cd docs-app && pnpm start`),
do:
 - `rm -rf node_modules`
 - `pnpm install`
 
It has been mentioned by the primary pnpm maintainer that this should be fixed. cause.. oof. lol

**Comment by nicolechung** [comment]
Nope still getting the `postcss-loader/dist` error.

Do I need to clear the virtual store maybe? (for pnpm)

`/Users/me/Library/pnpm/store/v3`
